### ISSUE TITLE
@user.update does NOT work when bcrypt is being used

### ISSUE THREAD

**Issue by rohanphillips** [learn-co-curriculum/rails-amusement-park#24] opened 2020-02-26 14:41 UTC
In the spec users_features_spec.rb, line 250, 260 and 270

@user.update is used but will not update the user because in order to update a record with an encrypted password the .update_attribute call needs to be made.

**Comment by lizbur10** [comment] 2020-04-01 18:00
Hi there,

I'm unable to reproduce the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information, I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed as completed by lizbur10** 2020-04-01 18:00 UTC
